<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Website resmi Pemerintah Desa Salam, Kecamatan Salam, Kabupaten Magelang.">
    <meta property="og:title" content="{{ $title ?? 'Desa Salam — Kecamatan Salam, Kabupaten Magelang' }}"><meta property="og:description" content="Mengenal, menelusuri, dan tumbuh bersama Desa Salam."><meta property="og:type" content="website">
    <title>{{ $title ?? 'Desa Salam — Kecamatan Salam, Kabupaten Magelang' }}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/site.css') }}">
</head>
<body>
<header class="site-header"><a class="brand" href="/"><span class="brand-mark">DS</span><span><b>Desa Salam</b><small>Kec. Salam, Kab. Magelang</small></span></a><button class="nav-toggle" aria-label="Buka menu" aria-expanded="false" onclick="document.querySelector('.nav-links').classList.toggle('is-open'); this.setAttribute('aria-expanded',this.getAttribute('aria-expanded')==='false')">☰</button><nav class="nav-links"><a href="/">Beranda</a><a href="/potensi">Potensi</a><a href="/layanan">Layanan</a><a href="/berita">Berita</a><a href="/umkm">UMKM</a><a href="/galeri">Galeri</a><a href="/kegiatan">Kegiatan</a></nav></header>
@yield('content')
<footer class="site-footer"><div class="footer-grid"><div class="footer-about"><a class="brand footer-brand" href="/"><span class="brand-mark">♧</span><span><b>Desa Salam</b><small>Kec. Salam, Kab. Magelang</small></span></a><p>Website resmi Pemerintah Desa Salam, Kecamatan Salam, Kabupaten Magelang, Jawa Tengah. Melayani dengan hangat, transparan, dan sepenuh hati untuk masyarakat.</p><address><a href="https://maps.google.com/?q=Kantor+Desa+Salam+Magelang"><span>⌖</span> Jl. Lapangan Desa Salam, Salam, Magelang 56484</a><a href="tel:+622932201234"><span>♧</span> (0293) 220 1234</a><a href="mailto:pemdes@desasalam.id"><span>✉</span> pemdes@desasalam.id</a></address><div class="socials"><a href="#kontak" aria-label="Facebook">FB</a><a href="#kontak" aria-label="Instagram">IG</a><a href="#kontak" aria-label="YouTube">YT</a></div></div><div class="footer-column"><h4>Halaman</h4><a href="/">Beranda</a><a href="/layanan">Layanan Desa</a><a href="/umkm">UMKM</a><a href="/galeri">Galeri</a><a href="/kegiatan">Kegiatan</a></div><div class="footer-column"><h4>Layanan</h4><a href="/layanan/surat-keterangan">Surat Keterangan</a><a href="/layanan/surat-domisili">Surat Domisili</a><a href="/layanan/surat-pengantar-ktp">Surat Pengantar KTP</a><a href="/layanan/surat-usaha">Surat Usaha</a><a href="/layanan/pengaduan-warga">Pengaduan Warga</a><a href="/layanan/info-dana-desa">Info Dana Desa</a><a href="/layanan/info-dana-desa">Laporan APBDes</a></div><div class="hours"><h4><i></i> Jam Pelayanan</h4><p><b>Senin – Kamis</b><br>08.00 – 14.00 WIB</p><hr><p><b>Jumat</b><br>08.00 – 11.00 WIB</p><small>*Sabtu, Minggu & hari libur nasional tutup.<br>Antrian dilayani pada hari kerja.</small></div></div><div class="footer-bottom"><span>© {{ date('Y') }} Pemerintah Desa Salam. Seluruh hak cipta dilindungi undang-undang. Informasi untuk warga.</span><nav><a href="#">Kebijakan Privasi</a><i>•</i><a href="#">Syarat & Ketentuan</a><i>•</i><a href="/sitemap.xml">Peta Situs</a></nav></div></footer>
</body></html>
